FROM node:6.9

RUN apt-get update && apt-get install apt-transport-https \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update && apt-get install yarn \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -gq ember-cli@2.11.1

USER node

RUN mkdir /home/node/app
WORKDIR /home/node/app
