FROM alpine:3.5

RUN wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.42.tar.gz \
    && tar xzf Image-ExifTool-10.42.tar.gz \
    && cd Image-ExifTool-10.42 \
    && apk --update add perl make \
    && perl Makefile.PL \
    && make install \
    && cd / \
    && rm -rf Image-ExifTool-10.42* \
    && rm -rf /var/cache/apk/*

RUN adduser -D exif
USER exif
WORKDIR /home/exif

ENTRYPOINT ["exiftool"]
CMD ["-help"]
